name: Kanar

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read
  pull-requests: write
  issues: write
  statuses: write

jobs:
  kanar:
    runs-on: ubuntu-latest
    steps:
      - uses: RampNetwork/kanar@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # this is passed automatically https://docs.github.com/en/actions/security-guides/automatic-token-authentication
          jira_token: ${{ secrets.JIRA_TOKEN }}
          jira_token_user: ${{ secrets.JIRA_TOKEN_USER }}
